### ISSUE TITLE
Cannot switch to Chinese/Japanese/Korean input method

### ISSUE THREAD

**Issue by fishfree** [SafeExamBrowser/seb-win-refactoring#18]
We usually firstly press Ctrl+Space to swith to the CJK input method, then input CJK characters. But now, it is invalid, and we can only input latin characters.

**Comment by dbuechel** [comment]
If I remember correctly, the IME once used to work with SEB 3.x. It might well be that this is another Windows bug, we will see that we can let MSFT know about the issue. Meanwhile, you could try to use the other kiosk mode (Disable Explorer Shell), it may be that the IME works on the standard desktop.

**Comment by dbuechel** [comment]
Any updates here?

**Comment by dbuechel** [comment]
Closed due to lack of feedback.

**Comment by fishfree** [comment]
@dbuechel Sorry for so late response! Please reopen this issue. I just test with the latest 3.2. The problem still exists. I even set the default language and input method mode both as Chinese, which means in any inputable text area, the default input method is Chinese as the screenshot below ( the inteface language of my Windows 10 is in English). But in the SEB, I still cannot input Chinese. Then I totally cannot use this brillant software :-(
![image](https://user-images.githubusercontent.com/1741341/125721367-cd45b033-f8e3-4b6f-b9d3-079bb26940f9.png)

> Meanwhile, you could try to use the other kiosk mode (Disable Explorer Shell), it may be that the IME works on the standard desktop.
How to configure that, please?

**Comment by dbuechel** [comment]
Could you please try to use kiosk mode Disable Explorer Shell to see whether that fixes the problem? The kiosk mode can be changed in the confiuration tool under tab Security: https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane.

**Comment by fishfree** [comment]
@dbuechel I changed to  use kiosk mode Disable Explorer Shell. The problem still exists.

**Comment by dbuechel** [comment]
Okay, we'll have a look at it once we have the time to do so.

**Comment by fishfree** [comment]
@dbuechel  Thank you very much! Maybe you yourself can install the Chinese language or input method to Windows 10 [this way](https://uniserveit.com/help-center/add-chinese-input-on-your-windows-10).  The shortcut of switching input method is usually Ctrl+Space or Ctrl+Shift or just left Shift.

**Comment by fishfree** [comment]
@dbuechel Hello, Damian! I also tried adding a new language in Windows 10 (build 19043.1149) as below:
![image](https://user-images.githubusercontent.com/1741341/126945388-fd11900b-ce95-41c6-a5ee-78d9090b4540.png)
And tried my Windows 10 kiosk mode, the input method switching works as normal by pressing the left Alt+Shift as the default setting as below:
![image](https://user-images.githubusercontent.com/1741341/126945538-25f1bc02-9892-48b4-9ad2-034ab5a67084.png)
However, in the SEB, I can use mouse to switch language, but still cannot switch Chinese input method, nor by pressing Ctrl+Space, nor by Shift:

**Comment by dbuechel** [comment]
Yes, you need to add a new language, otherwise it won't work. Did you verify that the IME (candidate characters bar as you name it) doesn't work in both kiosk modes?

**Comment by fishfree** [comment]
@dbuechel I test. The candidate characters bar works in kiosk mode, floating with the cursor.

**Comment by dbuechel** [comment]
So is there still an issue or is everything working now as you would need it?

**Comment by nvarghese-rm** [comment]
Hi 
Just adding my previous point here:
With the languages Chinese (simplified) and Japanese added, when I set Kiosk Mode as Disable Explorer Shell, the Japanese and Chinese options appeared in the SEB keyboard layout menu for both SEB Windows v3.2 and v2.3 . 
But the 'candidate character options' did not appear. The 'candidate character options'  would only appear if I disabled Kiosk mode entirely.

The Japanese language though is further complicated in that it has the option to switch the Japanese script as illustrated in screenshot by clicking on icon or mouse right click.

![Japanese Keyboard 2](https://user-images.githubusercontent.com/87759879/127586540-d0d50453-12b1-4d22-affb-d592358b3f4c.png)

**Comment by dbuechel** [comment]
Excellent, thanks for your input @nvarghese-rm. We will thus investigate whether we can bring at least the basic IME to work for Chinese and Japanese.

**Comment by dbuechel** [comment]
Okay, I investigated this issue a bit further and it unfortunately appears that we won't be able to fix the problem for now. In kiosk mode Create New Desktop, the IMEs don't work at all (neither Chinese nor Japanese) and the keyboard layouts aren't even loaded by SEB (or rather the .NET Framework doesn't load them under these circumstances). With kiosk mode Disable Explorer Shell, the Chinese as well as Japanese keyboard layouts are available and the Chinese characters actually appear after entering letters and then hitting space, however the IME (candidate character options) does not appear and Japanese still doesn't work at all. Only when the kiosk mode is disabled entirely, the IMEs appear to work.

This leads to the following preliminary conclusion: There is either a bug in Windows which prevents the IMEs to work correctly without the Windows shell (explorer.exe) running on the default and/or a custom desktop or there is some further configuration or precondition required to make IMEs work in a kiosk mode. Either way, this is definitely out of scope for version 3.3.2, but we'll see whether we can contact someone at MSFT and get help in potentially resolving this issue. As for Japanese specifically, supporting that keyboard layout and its very complicated IMEs will likely not happen any time soon.

**Comment by fishfree** [comment]
@dbuechel Hi, Damian. Is this issue solved in the latest 3.4 beta? esp. Chinese input method. However, another problem: under BYOD scenarios, users have to manually add another language in their Chinese version Microsoft, which is very hard to do for some unskillful users. Can we just enable the switching input method shortcuts to solve the problem?

**Comment by dbuechel** [comment]
This issue is still in the backlog for version 3.4.0, as I intend to contact MSFT and see whether there is anything we can do here. However, at the moment it looks that there won't be any support for these IMEs as already explained above.

> Can we just enable the switching input method shortcuts to solve the problem?

I'm not quite sure whether I understand you correctly, but if you're asking whether SEB can automatically install and activate Chinese as input language, then no, I'm afraid that's not possible.

**Comment by dbuechel** [comment]
Any further input or comments on this issue? Otherwise I'm afraid we'll need to mark this as won't fix for the moment.

**Comment by ruoshui-git** [comment]
As an alternative, for Chinese input, try Sogou Pinyin
