### ISSUE TITLE
SEB3 service fails to start

### ISSUE THREAD

**Issue by PKGeorgiev** [SafeExamBrowser/seb-win-refactoring#32]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
On some computers SEB3's service fails to start due to exception:
"Failed to start communication host for endpoint 'net.pipe://localhost/safeexambrowser/service' within 5 seconds"
This happens on some desktops / laptops regardless of hard drive type (HDD or SSD) when they start up.

**Steps to Reproduce**
It's random behavior.

**Expected Behavior**
SEB3's service should implement some retry logic to ensure service is up and running.

**Screenshots**

**Version Information**
 - OS: Windows 10 Professional, Version 1809
 - SEB-Version SEB 3.0.1.163

**Additional Context**
The only workaround was to create an automated  scheduled task (attached to specific event) that tries to start SEB's service within next 30 seconds. If interested, here is event filter:

```
<?xml version="1.0" encoding="UTF-8"?>
<QueryList>
   <Query Id="0" Path="System">
      <Select Path="System">*[EventData[Data[@Name='param1'] and (Data*='Safe Exam Browser Service')]]
and
*[System[(EventID='7034')]]</Select>
   </Query>
</QueryList>
```

Having this event filter you can deploy a scheduled task (in case you use Active Directory). Unfortunately this is not viable solution for student's computers.

Here is service's log:

```
2020-09-14 11:17:43.989 [04] - INFO: Initiating startup procedure...
2020-09-14 11:17:44.426 [04] - INFO: Starting auto-restore mechanism...
2020-09-14 11:17:44.755 [04] - INFO: [AutoRestoreMechanism] Started auto-restore mechanism.
2020-09-14 11:17:44.973 [04] - INFO: Starting communication host...
2020-09-14 11:17:45.208 [05] - DEBUG: [FeatureConfigurationBackup] No backup data found under 'C:\windows\system32\config\systemprofile\AppData\Local\SafeExamBrowser\Backup.bin'.
2020-09-14 11:17:45.270 [05] - INFO: [AutoRestoreMechanism] Nothing to restore, stopped auto-restore mechanism.
2020-09-14 11:17:49.207 [07] - DEBUG: [ServiceHost] Communication host is opening...
2020-09-14 11:17:53.910 [07] - DEBUG: [ServiceHost] Communication host has been opened.
2020-09-14 11:17:53.910 [07] - DEBUG: [ServiceHost] Successfully started communication host for endpoint 'net.pipe://localhost/safeexambrowser/service'.
2020-09-14 11:17:55.472 [04] - ERROR: Caught unexpected exception while performing operation 'CommunicationHostOperation'!

   Exception Message: Failed to start communication host for endpoint 'net.pipe://localhost/safeexambrowser/service' within 5 seconds!
   Exception Type: System.ServiceModel.CommunicationException

   at SafeExamBrowser.Communication.Hosts.BaseHost.Start() in C:\Users\appveyor\projects\seb-win-refactoring-l9ysdqd7kes2i06p\SafeExamBrowser.Communication\Hosts\BaseHost.cs:line 142
   at SafeExamBrowser.Core.Operations.CommunicationHostOperation.Perform() in C:\Users\appveyor\projects\seb-win-refactoring-l9ysdqd7kes2i06p\SafeExamBrowser.Core\Operations\CommunicationHostOperation.cs:line 42
   at SafeExamBrowser.Core.OperationModel.OperationSequence.Perform() in C:\Users\appveyor\projects\seb-win-refactoring-l9ysdqd7kes2i06p\SafeExamBrowser.Core\OperationModel\OperationSequence.cs:line 108

2020-09-14 11:17:55.488 [04] - INFO: Stopping communication host...
2020-09-14 11:17:55.488 [04] - DEBUG: [ServiceHost] Communication host is closing...
2020-09-14 11:17:56.082 [04] - DEBUG: [ServiceHost] Communication host has been closed.
2020-09-14 11:17:56.082 [04] - DEBUG: [ServiceHost] Terminated communication host for endpoint 'net.pipe://localhost/safeexambrowser/service'.
2020-09-14 11:17:56.082 [04] - INFO: Stopping auto-restore mechanism...
2020-09-14 11:17:56.082 [04] - INFO: [AutoRestoreMechanism] Auto-restore mechanism is not running.
2020-09-14 11:17:56.097 [04] - INFO: Service startup aborted!



```

**Comment by dbuechel** [comment]
Are you sure that there aren't any issues on your system which prevent WCF from working correctly? 5 seconds should be more than enough to start a communication host...

**Comment by PKGeorgiev** [comment]
I did some analysis. My reports show that SEB's service fails to start on about 10% - 15% of our PCs / laptops on random bases (btw, all machines were deployed using same Windows image).
If the service fails to start on a particular computer, a simple reboot solves the problem. But not all the times.
The automated task I've created executes with a 30 seconds delay and it seem to work. But I cannot deploy it to student's home computers.
I'm not sure, but since the OS is "under stress" at startup it sometimes may not be able to activate WCF services on time (within 5 seconds interval). My tests show that if I try to start the service 30-60 seconds after the OS was completely loaded - it starts normally.

**Comment by dbuechel** [comment]
I think we could increase it to 10 or 15 seconds, @danschlet ? What I would like to avoid is that users are stuck in front of a loading screen for a long time if something fails.

**Comment by PKGeorgiev** [comment]
@dbuechel, what do you mean by saying "What I would like to avoid is that users are stuck in front of a loading screen for a long time if something fails."?

**Comment by dbuechel** [comment]
If the timeout is e.g. one minute, users would be stuck for one minute in front of a loading screen when in reality it is long clear that something has failed. I thought that 5 seconds would be enough to start the WCF host, as I recall that it happens almost instantaneously on my machine (e.g. while debugging).

**Comment by dbuechel** [comment]
Sorry, I was mistaken here. As it is the timeout for the service, users shouldn't notice it as long as it isn't too high (e.g. one minute, in which the OS is started and a user tries to start SEB before the service is ready).

**Comment by dbuechel** [comment]
We will increase the timeout for the service communication host to 15 seconds for version 3.1.

**Comment by dbuechel** [comment]
Should be fixed with release version 3.1.0.

**Comment by naufalw** [comment]
Sorry, but it still happened to me in Build 3.1.1.250
the error is still the same

Runtime log : 
`/* Safe Exam Browser, Version 3.1.1 (x64), Build 3.1.1.250
/* Copyright © 2020 ETH Zürich, Educational Development and Technology (LET)
/* 
/* Please visit https://www.github.com/SafeExamBrowser for more information.

# Application started at 2021-02-09 12.01.04.693
# Running on Windows 10, Microsoft Windows NT 10.0.18363.0 (x64)
# Computer 'DESKTOP-6DS3S3I' is a X X453SA manufactured by ASUSTeK COMPUTER INC.
# Runtime-ID: efb44c41-83a9-4646-b8ce-70b685b8c0bd

2021-02-09 12.01.12.970 [07] - INFO: Initiating startup procedure...
2021-02-09 12.01.13.157 [07] - INFO: Loading text data...
2021-02-09 12.01.13.157 [07] - DEBUG: [Text] System language is 'en', trying to load data...
2021-02-09 12.01.13.267 [07] - DEBUG: [Text] Data successfully loaded.
2021-02-09 12.01.13.267 [07] - INFO: Starting communication host...
2021-02-09 12.01.14.611 [10] - DEBUG: [RuntimeHost] Communication host is opening...
2021-02-09 12.01.18.751 [07] - ERROR: Caught unexpected exception while performing operation 'CommunicationHostOperation'!

   Exception Message: Failed to start communication host for endpoint 'net.pipe://localhost/safeexambrowser/runtime/88521e21-a581-4ebf-9910-23d46d4b48fc' within 5 seconds!
   Exception Type: System.ServiceModel.CommunicationException

   at SafeExamBrowser.Communication.Hosts.BaseHost.Start() in C:\Users\appveyor\projects\seb-win-refactoring-3pv4craowibjxry0\SafeExamBrowser.Communication\Hosts\BaseHost.cs:line 142
   at SafeExamBrowser.Core.Operations.CommunicationHostOperation.Perform() in C:\Users\appveyor\projects\seb-win-refactoring-3pv4craowibjxry0\SafeExamBrowser.Core\Operations\CommunicationHostOperation.cs:line 42
   at SafeExamBrowser.Core.OperationModel.OperationSequence.Perform() in C:\Users\appveyor\projects\seb-win-refactoring-3pv4craowibjxry0\SafeExamBrowser.Core\OperationModel\OperationSequence.cs:line 108

2021-02-09 12.01.18.782 [07] - INFO: Stopping communication host...
2021-02-09 12.01.18.782 [07] - DEBUG: [RuntimeHost] Communication host is closing...
2021-02-09 12.01.19.235 [07] - DEBUG: [RuntimeHost] Communication host has been closed.
2021-02-09 12.01.19.751 [07] - DEBUG: [RuntimeHost] Terminated communication host for endpoint 'net.pipe://localhost/safeexambrowser/runtime/88521e21-a581-4ebf-9910-23d46d4b48fc'.
2021-02-09 12.01.19.751 [07] - INFO: Application startup aborted!


2021-02-09 12.02.59.403 [07] - INFO: Initiating shutdown procedure...
2021-02-09 12.02.59.403 [07] - INFO: Application successfully finalized.

# Application terminated at 2021-02-09 12.03.00.727
`

**Comment by dbuechel** [comment]
Make sure WCF is working correctly on your machine. On a normal machine, starting the WCF host for the runtime should never take more than 5 seconds. If you have a lot of software running besides SEB when starting it, try to close everything else before attempting to start SEB.

**Comment by tanmaya-hub** [comment]
Hi dbuechel, I am a developer. I was going through the code of SEB. Can you please let me know what is the role of these 2 WCF services? When a message is sent using Send Method where it goes
net.pipe://localhost/safeexambrowser/client
net.pipe://localhost/safeexambrowser/runtime

**Comment by tbang188** [comment]
I can start service 
![image](https://user-images.githubusercontent.com/71419968/142972296-b36ae39e-c419-44a7-b893-227c159f4e14.png)
Althought I start service on windows serivce
![image](https://user-images.githubusercontent.com/71419968/142972360-2b2cb233-bb05-43cd-9679-f83bb92fd365.png)
Who can help me how to start it ?
 Thank you so much

**Comment by Tinoyyus** [comment]
for some reason SEB cannot configure

**Comment by Tinoyyus** [comment]
please help

**Comment by Tinoyyus** [comment]
Please check this out 
[2024-09-09_17h06m01s_Client.log](https://github.com/user-attachments/files/16929795/2024-09-09_17h06m01s_Client.log)
[2024-09-09_17h06m01s_Runtime.log](https://github.com/user-attachments/files/16929799/2024-09-09_17h06m01s_Runtime.log)
